### ISSUE TITLE
Illegal argument causes set_ee_cartesian_trajectory to crash

### ISSUE THREAD

**Issue by harshitsankhla** [Interbotix/interbotix_ros_toolboxes#17]
https://github.com/Interbotix/interbotix_ros_toolboxes/blob/1ed10f99f9ce7d5d77f65b5756d8f3f7a06bdc1e/interbotix_common_toolbox/interbotix_common_modules/src/interbotix_common_modules/angle_manipulation.py#L52

np.identity() does not have any keyword `like` (this keyword has been introduced from numpy v1.20)

this crashes the set_ee_cartesian_trajectory method 
https://github.com/Interbotix/interbotix_ros_toolboxes/blob/1ed10f99f9ce7d5d77f65b5756d8f3f7a06bdc1e/interbotix_xs_toolbox/interbotix_xs_modules/src/interbotix_xs_modules/arm.py#L247

**Comment by LSinterbotix** [comment]
If your numpy version is lower than what is required, you should be able to upgrade it by running the following command:

```console
$ pip install numpy --upgrade # or pip3 if on noetic
```

Let us know if this does not resolve your issue.
