### ISSUE TITLE
Crash on get_set_landmarks function in Landmark

### ISSUE THREAD

**Issue by wermthib** [Interbotix/interbotix_ros_toolboxes#36]
When I first ran the [`nav_to_landmark`](https://github.com/Interbotix/interbotix_ros_rovers/blob/main/interbotix_ros_xslocobots/examples/interbotix_xslocobot_landmark_nav/scripts/nav_to_landmark) script, I got an error `TypeError: unhashable type: 'Landmark'`.

By looking at the log file and the code, the line that threw the error is [this one](https://github.com/Interbotix/interbotix_ros_toolboxes/blob/main/interbotix_common_toolbox/interbotix_landmark_modules/src/interbotix_landmark_modules/landmark.py#L424)

```python
def get_set_landmarks(self):
        """returns the list of seen landmarks
        
        :return: list of seen landmarks in the Collection
        :rtype: list of Landmarks
        """
        return set([l for l in self.data.values() if l.tf_set_])
```

I don't know why Landmark is not hashable on my pc, but I replaced `set` with `list` to fix the issue and it worked fine.

**Comment by LSinterbotix** [comment]
@wermthib Thanks for reporting this! Please see if the changes in [82ded8c](https://github.com/Interbotix/interbotix_ros_toolboxes/commit/82ded8c525e02201e9e4fd0e40624a942db6435c) solve the issue.

**Comment by wermthib** [comment]
@LSinterbotix Yes it works! Thanks!
