### ISSUE TITLE
[Question]: Arm calibration

### ISSUE THREAD

**Issue by Zhuomin-Zhou** [Interbotix/interbotix_ros_toolboxes#39]
### Question

Hi,

Is there a recommended method to calibrate the manipulator?
In my test, I found about 3 to 4 mm differences in the x-direction and 2 mm differences in the y-direction. 

### Robot Model

wx250s

### Operating System

Ubuntu 20.04

### ROS Version

ROS2 Galactic

**Comment by LSinterbotix** [comment]
We have no recommended method for calibration but you can find tips on increasing accuracy in the links below:
- [Troubleshooting - Increasing Motor Accuracy](https://www.trossenrobotics.com/docs/interbotix_xsarms/troubleshooting/index.html#increase-motor-accuracy)
- [Issues - Improving Accuracy During Pose Execution](https://github.com/Interbotix/interbotix_ros_manipulators/issues/24)

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.

**Comment by Zhuomin-Zhou** [comment]
Hi @LSinterbotix,

I don't have any further questions.
I appreciate your help!

Regards,
Min
